# Generated by Django 6.0 on 2026-02-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("poc", models.CharField(max_length=100)),
                ("ntn", models.CharField(max_length=20, unique=True)),
                ("address", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Driver Name")),
                (
                    "father_name",
                    models.CharField(max_length=100, verbose_name="Father Name"),
                ),
                ("address", models.TextField(verbose_name="Address")),
                ("mobile", models.CharField(max_length=20, verbose_name="Mobile #")),
                (
                    "cnic",
                    models.CharField(max_length=15, unique=True, verbose_name="CNIC #"),
                ),
                ("cnic_expiry", models.DateField(verbose_name="CNIC Expiry")),
                (
                    "license_number",
                    models.CharField(max_length=50, verbose_name="License Number"),
                ),
                ("license_expiry", models.DateField(verbose_name="License Expiry")),
                ("reference1_name", models.CharField(blank=True, max_length=100)),
                ("reference1_mobile", models.CharField(blank=True, max_length=20)),
                ("reference2_name", models.CharField(blank=True, max_length=100)),
                ("reference2_mobile", models.CharField(blank=True, max_length=20)),
                ("joining_date", models.DateField(verbose_name="Joining Date")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("slip_no", models.CharField(blank=True, max_length=50, null=True)),
                ("fuel_liter", models.FloatField(default=0)),
                ("fuel_amount", models.FloatField(default=0)),
                ("pump_name", models.CharField(blank=True, max_length=100, null=True)),
                ("toll_tax", models.FloatField(default=0)),
                ("inam", models.FloatField(default=0)),
                ("police", models.FloatField(default=0)),
                ("food", models.FloatField(default=0)),
                ("card", models.FloatField(default=0)),
                ("maintenance", models.FloatField(default=0)),
                ("other", models.FloatField(default=0)),
                ("total_diesel", models.FloatField(default=0)),
                ("total_expense", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance_km", models.PositiveIntegerField()),
                ("route_code", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_mode",
                    models.CharField(
                        choices=[
                            ("OWN", "Own"),
                            ("RENTAL", "Rental"),
                            ("FIXED", "Fixed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=20, unique=True)),
                (
                    "current_location",
                    models.CharField(blank=True, default="Karachi", max_length=100),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Suzuki Dry", "Suzuki Dry"),
                            ("Suzuki Reefer", "Suzuki Reefer"),
                            ("Shahzore Dry", "Shahzore Dry"),
                            ("Shahzore Reefer", "Shahzore Reefer"),
                            ("14ft Dry", "14ft Dry"),
                            ("14ft Reefer", "14ft Reefer"),
                            ("16ft Dry", "16ft Dry"),
                            ("16ft Reefer", "16ft Reefer"),
                            ("18ft Dry", "18ft Dry"),
                            ("18ft Reefer", "18ft Reefer"),
                            ("20ft Dry", "20ft Dry"),
                            ("20ft Reefer", "20ft Reefer"),
                            ("40ft Dry", "40ft Dry"),
                            ("40ft Reefer", "40ft Reefer"),
                            ("45ft Dry", "45ft Dry"),
                            ("45ft Reefer", "45ft Reefer"),
                            ("50ft Dry", "50ft Dry"),
                            ("50ft Reefer", "50ft Reefer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("engine_no", models.CharField(blank=True, max_length=50, null=True)),
                ("chassis_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "container_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wheeler",
                    models.CharField(
                        choices=[
                            ("2x2", "2x2"),
                            ("2x4", "2x4"),
                            ("2x8", "2x8"),
                            ("6x8", "6x8"),
                            ("6x12", "6x12"),
                            ("6x16", "6x16"),
                        ],
                        max_length=10,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=30)),
                ("sindh_permit_expiry", models.DateField(blank=True, null=True)),
                ("punjab_permit_expiry", models.DateField(blank=True, null=True)),
                ("kpk_permit_expiry", models.DateField(blank=True, null=True)),
                ("balochistan_permit_expiry", models.DateField(blank=True, null=True)),
                ("fitness_expiry_sindh", models.DateField(blank=True, null=True)),
                ("fitness_expiry_punjab", models.DateField(blank=True, null=True)),
                ("fitness_expiry_kpk", models.DateField(blank=True, null=True)),
                ("fitness_expiry_balochistan", models.DateField(blank=True, null=True)),
                ("driver_name", models.CharField(blank=True, max_length=100)),
                ("driver_cnic", models.CharField(blank=True, max_length=15)),
                ("driver_mobile", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("current_km", models.PositiveIntegerField(default=0)),
                ("last_meter_update", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[("OIL", "Oil Change"), ("TIRE", "Tire Change")],
                        max_length=10,
                    ),
                ),
                ("change_date", models.DateField()),
                ("change_km", models.PositiveIntegerField()),
                ("next_due_km", models.PositiveIntegerField(editable=False)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("poc", models.CharField(max_length=100)),
                ("ntn", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VendorRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ClientRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fuel_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="masters.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remarks", models.TextField(blank=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="masters.driver"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("salary_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid", models.BooleanField(default=False)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="masters.driver"
                    ),
                ),
            ],
        ),
    ]
