# Generated by Django 6.0 on 2026-02-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0001_initial"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="operations.trip",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_to",
                to="masters.city",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes_from",
                to="masters.city",
            ),
        ),
        migrations.AddField(
            model_name="clientrate",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masters.route"
            ),
        ),
        migrations.AddField(
            model_name="vehiclemaintenance",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masters.vehicle"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="masters.vendor",
            ),
        ),
        migrations.AddField(
            model_name="vendorrate",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masters.route"
            ),
        ),
        migrations.AddField(
            model_name="vendorrate",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="masters.vendor"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientrate",
            unique_together={("client", "route")},
        ),
    ]
