# Generated by Django 6.0 on 2026-02-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="driver_cnic",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="driver_mobile",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="driver_name",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Select driver from the registered list",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="masters.driver",
            ),
        ),
    ]
