# Generated by Django 6.0 on 2026-02-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0003_remove_vehicle_driver_cnic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="total_diesel",
        ),
        migrations.AddField(
            model_name="expense",
            name="fuel_rate",
            field=models.FloatField(default=0, help_text="Rate per liter"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="fuel_amount",
            field=models.FloatField(default=0, help_text="Total fuel cost"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="fuel_liter",
            field=models.FloatField(default=0, help_text="Total Liters filled"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="total_expense",
            field=models.FloatField(default=0, editable=False),
        ),
    ]
