# Generated by Django 6.0 on 2026-07-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0005_vendor_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="maintenance_type",
            field=models.CharField(
                choices=[
                    ("OIL", "Oil Change"),
                    ("TIRE", "Tire Change"),
                    ("BRAKE", "Brake Repair"),
                    ("OTHER", "General Service"),
                ],
                max_length=10,
            ),
        ),
    ]
