# Generated by Django 6.0 on 2026-07-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0006_alter_vehiclemaintenance_maintenance_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driversalary",
            name="salary_amount",
        ),
        migrations.AddField(
            model_name="driversalary",
            name="absent_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="advance_deduction",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="attendance_allowance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="base_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Base / Fixed Salary",
            ),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="designation",
            field=models.CharField(default="Driver", max_length=30),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="earned_base_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="emp_id",
            field=models.CharField(blank=True, max_length=20, verbose_name="Emp ID"),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="net_payable_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="new_advance_taken",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="per_day_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="present_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="previous_advance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="status",
            field=models.CharField(default="Active", max_length=20),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="sundays",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="driversalary",
            name="total_gross_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
