# Generated by Django 6.0 on 2026-07-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0007_remove_driversalary_salary_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="billing_company",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Mini Truck", "Mini Truck"),
                    ("Suzuki Dry", "Suzuki Dry"),
                    ("Suzuki Reefer", "Suzuki Reefer"),
                    ("Shahzore Dry", "Shahzore Dry"),
                    ("Shahzore Reefer", "Shahzore Reefer"),
                    ("10ft Dry", "10ft Dry"),
                    ("10ft Reefer", "10ft Reefer"),
                    ("14ft Dry", "14ft Dry"),
                    ("14ft Reefer", "14ft Reefer"),
                    ("16ft Dry", "16ft Dry"),
                    ("16ft Reefer", "16ft Reefer"),
                    ("17ft Dry", "17ft Dry"),
                    ("17ft Reefer", "17ft Reefer"),
                    ("18ft Dry", "18ft Dry"),
                    ("18ft Reefer", "18ft Reefer"),
                    ("20ft Dry", "20ft Dry"),
                    ("20ft Reefer", "20ft Reefer"),
                    ("22ft Dry", "22ft Dry"),
                    ("22ft Reefer", "22ft Reefer"),
                    ("24ft Dry", "24ft Dry"),
                    ("24ft Reefer", "24ft Reefer"),
                    ("34ft Dry", "34ft Dry"),
                    ("34ft Reefer", "34ft Reefer"),
                    ("40ft Dry", "40ft Dry"),
                    ("40ft Reefer", "40ft Reefer"),
                    ("45ft Dry", "45ft Dry"),
                    ("45ft Reefer", "45ft Reefer"),
                    ("50ft Dry", "50ft Dry"),
                    ("50ft Reefer", "50ft Reefer"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="wheeler",
            field=models.CharField(
                choices=[
                    ("2x2", "2x2"),
                    ("2x4", "2x4"),
                    ("2x8", "2x8"),
                    ("6x8", "6x8"),
                    ("6x12", "6x12"),
                    ("6x16", "6x16"),
                    ("6", "6 Wheeler"),
                    ("14", "14 Wheeler"),
                ],
                max_length=10,
            ),
        ),
    ]
