# Generated by Django 6.0 on 2026-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0008_client_billing_company_alter_vehicle_vehicle_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="employee_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Employee ID"
            ),
        ),
    ]
