# Generated by Django 6.0 on 2026-07-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0009_driver_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="employee_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, verbose_name="Employee ID"
            ),
        ),
    ]
