# Generated by Django 6.0 on 2026-07-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0010_alter_driver_employee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("date", models.DateField()),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("OIL", "Oil Change"),
                            ("WHEEL", "Wheel Service"),
                            ("BRAKE", "Brake Setting"),
                            ("ELECTRICAL", "Electrical"),
                            ("BODY", "Denting / Painting"),
                            ("GENERAL", "General Service"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        max_length=15,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "odometer_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Odometer (KM)"
                    ),
                ),
                (
                    "next_service_due_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Next Service Due (KM)"
                    ),
                ),
                ("spare_parts_vendor", models.CharField(blank=True, max_length=100)),
                (
                    "spare_parts_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "vendor_payment_status",
                    models.CharField(
                        choices=[("UNPAID", "Unpaid"), ("PAID", "Paid")],
                        default="UNPAID",
                        max_length=10,
                        verbose_name="Vendor Payment Status",
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "bill_ref",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Payment Date / Bill Ref",
                    ),
                ),
                (
                    "unpaid_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Unpaid Balance (PKR)",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_jobs",
                        to="masters.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaintenancePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_used", models.CharField(max_length=150)),
                ("quantity_used", models.PositiveIntegerField(default=1)),
                (
                    "part_source",
                    models.CharField(
                        choices=[
                            ("OWN", "Own Inventory"),
                            ("VENDOR", "Direct Vendor Purchase"),
                        ],
                        default="OWN",
                        max_length=10,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_used",
                        to="masters.maintenancejob",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="VehicleMaintenance",
        ),
    ]
