# Generated by Django 6.0 on 2026-07-21 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0011_maintenancejob_maintenancepart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_id",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "part_name",
                    models.CharField(max_length=150, verbose_name="Part Name"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GREASE", "Grease"),
                            ("NUT_BOLT", "Nut Bolt"),
                            ("FLUID", "Fluid"),
                            ("SEAL", "Seal"),
                            ("PIPE", "Pipe"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "stock_level",
                    models.PositiveIntegerField(default=0, verbose_name="Stock Level"),
                ),
                (
                    "reorder_point",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Reorder Point"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "total_used",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Total Used"
                    ),
                ),
                (
                    "remaining_stock",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Remaining Stock"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Parts Inventory",
                "ordering": ["part_name"],
            },
        ),
        migrations.AddField(
            model_name="maintenancepart",
            name="inventory_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a Parts Inventory row so 'Own Inventory' usage draws down its stock",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usages",
                to="masters.partsinventory",
            ),
        ),
    ]
