# Generated by Django 6.0 on 2026-07-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0012_partsinventory_maintenancepart_inventory_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["origin__name", "destination__name"]},
        ),
    ]
