# Generated by Django 6.0 on 2026-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0013_alter_city_options_alter_driver_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="tt_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="TT Hours",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="code",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance_km",
            field=models.PositiveIntegerField(verbose_name="KMs"),
        ),
        migrations.AlterField(
            model_name="route",
            name="route_code",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
