# Generated by Django 6.0 on 2026-08-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0016_vehicle_type_wheeler_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="dedicated_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dedicated_vehicles",
                to="masters.client",
                verbose_name="Dedicated to Client",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="driver2",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional second driver assigned to this vehicle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles_as_second_driver",
                to="masters.driver",
                verbose_name="Second Driver",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="m_tag",
            field=models.CharField(blank=True, max_length=50, verbose_name="M-Tag #"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="starting_km",
            field=models.PositiveIntegerField(default=0, verbose_name="Starting KMs"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("MAINTENANCE", "Under Maintenance"),
                    ("IDLE", "Idle"),
                    ("INACTIVE", "Inactive"),
                ],
                default="ACTIVE",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="vehicletyre",
            name="installed_km",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Kilometer"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="current_km",
            field=models.PositiveIntegerField(default=0, verbose_name="Current KMs"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
