# Generated by Django 6.0 on 2026-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0017_vehicle_dedicated_client_vehicle_driver2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="owner",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="weight_capacity",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Weight Capacity"
            ),
        ),
        migrations.AddField(
            model_name="vehicletyre",
            name="make",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tyre Make"
            ),
        ),
        migrations.AddField(
            model_name="vehicletyre",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
