# Generated by Django 6.0 on 2026-08-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0018_vehicle_owner_vehicle_weight_capacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="last_meter_update",
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_mode",
            field=models.CharField(
                choices=[("OWN", "Own"), ("RENTAL", "Rental")],
                default="OWN",
                max_length=10,
            ),
        ),
    ]
