# Generated by Django 6.0 on 2026-08-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0019_remove_vehicle_last_meter_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="poc",
        ),
        migrations.AddField(
            model_name="vendor",
            name="billing_period",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Billing Period"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="poc1_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="poc1_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Point of Contact 1"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="poc1_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone / Mobile Number"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="poc2_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="poc2_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Point of Contact 2"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="poc2_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone / Mobile Number"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="stn",
            field=models.CharField(blank=True, max_length=30, verbose_name="STN #"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="term_of_service",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Term of Service"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Supplier Name"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="ntn",
            field=models.CharField(blank=True, max_length=30, verbose_name="NTN #"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="supplier_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendors",
                to="masters.suppliertype",
            ),
        ),
    ]
