# Generated by Django 6.0 on 2026-08-04 05:54

import django.db.models.deletion
from django.db import migrations, models


def copy_poc_to_poc1_name(apps, schema_editor):
    Client = apps.get_model("masters", "Client")
    for client in Client.objects.exclude(poc=""):
        client.poc1_name = client.poc
        client.save(update_fields=["poc1_name"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0020_suppliertype_remove_vendor_phone_remove_vendor_poc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="billing_period",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Billing Period"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="poc1_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="client",
            name="poc1_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Point of Contact 1"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="poc1_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone / Mobile Number"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="poc2_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="client",
            name="poc2_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Point of Contact 2"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="poc2_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone / Mobile Number"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="stn",
            field=models.CharField(blank=True, max_length=30, verbose_name="STN #"),
        ),
        migrations.AddField(
            model_name="client",
            name="term_of_service",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Terms of Service"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="ntn",
            field=models.CharField(max_length=20, unique=True, verbose_name="NTN #"),
        ),
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="masters.clienttype",
            ),
        ),
        migrations.RunPython(copy_poc_to_poc1_name, noop),
        migrations.RemoveField(
            model_name="client",
            name="poc",
        ),
    ]
