# Generated by Django 6.0 on 2026-08-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0021_clienttype_remove_client_poc_client_billing_period_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="term_of_service",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Terms of Service"
            ),
        ),
    ]
