# Generated by Django 6.0 on 2026-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0022_alter_vendor_term_of_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
