# Generated by Django 6.0 on 2026-08-06 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0024_clientrate_fuel_price_revision_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DedicatedRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fixed_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Fixed Cost"
                    ),
                ),
                ("month", models.DateField(verbose_name="Month")),
                (
                    "fuel_avg",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Fuel Avg (Km/Ltr)"
                    ),
                ),
                (
                    "fuel_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Fuel Price"
                    ),
                ),
                (
                    "variable_cost",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="Variable Cost (Rs/Km)",
                    ),
                ),
                (
                    "distance_mode",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard (from Route)"),
                            ("ACTUAL", "Actual (from Job Orders)"),
                            ("TRACKER", "Tracker (manual)"),
                        ],
                        default="STANDARD",
                        max_length=10,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Distance (Km)"
                    ),
                ),
                ("effective_date", models.DateField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dedicated_rates",
                        to="masters.client",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedicated_rates",
                        to="masters.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedicated_rates",
                        to="masters.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["route__route_code", "-effective_date", "-id"],
            },
        ),
    ]
