# Generated by Django 6.0 on 2026-08-07 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0026_rename_driver_to_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Select staff member from the registered list",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="masters.staff",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="driver2",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional second staff member assigned to this vehicle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles_as_second_driver",
                to="masters.staff",
                verbose_name="Second Driver",
            ),
        ),
    ]
