# Generated by Django 6.0 on 2026-08-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0027_alter_vehicle_driver_alter_vehicle_driver2"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMonthlyAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(verbose_name="Reporting Month")),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_closed", models.BooleanField(default=False)),
                ("closed_date", models.DateField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_accounts",
                        to="masters.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "unique_together": {("staff", "month")},
            },
        ),
        migrations.CreateModel(
            name="StaffAccountEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "expense",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="masters.staffmonthlyaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="StaffAttendanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("LEAVE", "Leave"),
                            ("ABSENT", "Absent"),
                        ],
                        default="PRESENT",
                        max_length=10,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="masters.staffmonthlyaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("account", "date")},
            },
        ),
    ]
