# Generated by Django 6.0 on 2026-08-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0028_staffmonthlyaccount_staffaccountentry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="masters.fuelproduct",
            ),
        ),
        migrations.CreateModel(
            name="VendorFuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Fuel Price"
                    ),
                ),
                ("effective_date", models.DateField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendor_prices",
                        to="masters.fuelproduct",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_prices",
                        to="masters.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-id"],
            },
        ),
    ]
