# Generated by Django 6.0 on 2026-08-10 10:59

from django.db import migrations


def seed_fuel_products(apps, schema_editor):
    FuelProduct = apps.get_model("masters", "FuelProduct")
    for name in ("HI CETANE DIESEL", "PREMIER EURO5"):
        FuelProduct.objects.get_or_create(name=name)


def remove_seeded_fuel_products(apps, schema_editor):
    FuelProduct = apps.get_model("masters", "FuelProduct")
    FuelProduct.objects.filter(name__in=("HI CETANE DIESEL", "PREMIER EURO5")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0029_fuelproduct_vehicle_fuel_type_vendorfuelprice"),
    ]

    operations = [
        migrations.RunPython(seed_fuel_products, remove_seeded_fuel_products),
    ]
