# Generated by Django 6.0 on 2026-08-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0030_seed_fuel_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrate",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_rates",
                to="masters.vehicletype",
            ),
        ),
        migrations.AddField(
            model_name="clientrate",
            name="weight_tons",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Weight (Tons)",
            ),
        ),
        migrations.AddField(
            model_name="dedicatedrate",
            name="vehicle_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dedicated_rates",
                to="masters.vehicletype",
            ),
        ),
        migrations.AddField(
            model_name="dedicatedrate",
            name="weight_tons",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Weight (Tons)",
            ),
        ),
    ]
