# Generated by Django 6.0 on 2026-08-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0031_clientrate_vehicle_type_clientrate_weight_tons_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="tt_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="Transit Duration (Hours)",
            ),
        ),
    ]
