# Generated by Django 6.0 on 2026-09-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0032_alter_route_tt_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientrate",
            name="fuel_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_rates",
                to="masters.fuelproduct",
            ),
        ),
    ]
