# Generated by Django 6.0 on 2026-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0033_clientrate_fuel_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientrate",
            name="current_fuel_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Current Fuel Price"
            ),
        ),
        migrations.AlterField(
            model_name="clientrate",
            name="current_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Current Rate"
            ),
        ),
        migrations.AlterField(
            model_name="clientrate",
            name="effective_percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Effective %"
            ),
        ),
        migrations.AlterField(
            model_name="clientrate",
            name="fuel_price_change_percent",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name="clientrate",
            name="rate_adjustment",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clientrate",
            name="rate_subject_to_revision",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clientrate",
            name="updated_fuel_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Updated Fuel Price"
            ),
        ),
        migrations.AlterField(
            model_name="clientrate",
            name="updated_trip_cost",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name="clientrate",
            name="weight_tons",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Weight (Tons)",
            ),
        ),
    ]
