# Generated by Django 6.0 on 2026-09-24 08:42

import django.db.models.deletion
from django.db import migrations, models


CLIENT_NAME = "Five Star 3PL SERVICES"


def create_five_star_sub_categories(apps, schema_editor):
    """Five Star bills two units on different rates: ASSIA (the fuel-linked
    rates already on file) and REVO (fixed rates, entered separately). Every
    existing Five Star rate becomes ASSIA; REVO starts with none."""
    Client = apps.get_model("masters", "Client")
    ClientSubCategory = apps.get_model("masters", "ClientSubCategory")
    ClientRate = apps.get_model("masters", "ClientRate")
    client = Client.objects.filter(name__iexact=CLIENT_NAME).first()
    if not client:
        return
    assia, _ = ClientSubCategory.objects.get_or_create(client=client, name="ASSIA")
    ClientSubCategory.objects.get_or_create(client=client, name="REVO")
    ClientRate.objects.filter(client=client, sub_category__isnull=True).update(sub_category=assia)


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0035_fuel_rate_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="masters.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="clientrate",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rates",
                to="masters.clientsubcategory",
                verbose_name="Sub-Category",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientsubcategory",
            constraint=models.UniqueConstraint(
                fields=("client", "name"), name="uniq_client_subcategory_name"
            ),
        ),
        migrations.RunPython(create_five_star_sub_categories, migrations.RunPython.noop),
    ]
