# Generated by Django 6.0 on 2026-09-24 09:28

from django.db import migrations, models


def flag_five_star(apps, schema_editor):
    """Five Star is the client with separate units (ASSIA / REVO)."""
    Client = apps.get_model("masters", "Client")
    Client.objects.filter(name__iexact="Five Star 3PL SERVICES").update(has_sub_categories=True)


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0036_client_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="has_sub_categories",
            field=models.BooleanField(default=False, verbose_name="Has Sub-Categories"),
        ),
        migrations.AddField(
            model_name="clientrate",
            name="rate_type",
            field=models.CharField(
                choices=[("AUTO", "Auto (fuel-linked)"), ("FIXED", "Fixed")],
                default="AUTO",
                max_length=5,
            ),
        ),
        migrations.RunPython(flag_five_star, migrations.RunPython.noop),
    ]
