# Generated by Django 6.0 on 2026-09-24 10:45

import django.db.models.deletion
from django.db import migrations, models


# Danish's stopover charges: (vehicle type, within Karachi, other cities).
SEED = [
    ("16FT DRY", 3000, 5000),
    ("20FT DRY", 3000, 5000),
    ("40FT DRY", None, 15000),
]


def seed_stopover_rates(apps, schema_editor):
    VehicleType = apps.get_model("masters", "VehicleType")
    StopoverRate = apps.get_model("masters", "StopoverRate")
    for name, khi, other in SEED:
        vt, _ = VehicleType.objects.get_or_create(name=name)
        for zone, amount in (("KHI", khi), ("OTHER", other)):
            if amount is not None:
                StopoverRate.objects.get_or_create(vehicle_type=vt, zone=zone, defaults={"amount": amount})


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0037_client_rate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="StopoverRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[("KHI", "Within Karachi"), ("OTHER", "Other Cities")],
                        max_length=5,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stopover_rates",
                        to="masters.vehicletype",
                    ),
                ),
            ],
            options={
                "ordering": ["vehicle_type__name", "zone"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vehicle_type", "zone"),
                        name="uniq_stopover_rate_type_zone",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_stopover_rates, migrations.RunPython.noop),
    ]
