# Generated by Django 6.0 on 2026-09-25 11:24

from django.db import migrations, models

# Real-world province of every city already on file (by name) - a new city
# still picks its own province on the Register City form.
KNOWN_PROVINCES = {
    "BAHAWALPUR": "PUNJAB", "FAISALABAD": "PUNJAB", "GUJRANWALA": "PUNJAB",
    "HYDERABAD": "SINDH", "KARACHI": "SINDH", "LAHORE": "PUNJAB",
    "LARKANA": "SINDH", "MULTAN": "PUNJAB", "PESHAWAR": "KPK",
    "QUETTA": "BALOCHISTAN", "SAHIWAL": "PUNJAB", "SARGODHA": "PUNJAB",
    "SHIKARPUR": "SINDH", "SIALKOT": "PUNJAB",
    # Islamabad is federal territory, not one of the 4 provinces - left blank.
}


def backfill_provinces(apps, schema_editor):
    City = apps.get_model("masters", "City")
    for name, province in KNOWN_PROVINCES.items():
        City.objects.filter(name=name).update(province=province)


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0040_rename_assia_asaia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Company Name")),
                (
                    "poc1_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Point of Contact 1"
                    ),
                ),
                (
                    "poc1_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone / Mobile Number"
                    ),
                ),
                (
                    "poc1_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "poc2_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Point of Contact 2"
                    ),
                ),
                (
                    "poc2_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone / Mobile Number"
                    ),
                ),
                (
                    "poc2_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "ntn",
                    models.CharField(blank=True, max_length=20, verbose_name="NTN #"),
                ),
                (
                    "stn",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Tax Reg # (STN)"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="city",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINDH", "Sindh"),
                    ("PUNJAB", "Punjab"),
                    ("BALOCHISTAN", "Balochistan"),
                    ("KPK", "Khyber Pakhtunkhwa"),
                ],
                max_length=15,
            ),
        ),
        migrations.RunPython(backfill_provinces, migrations.RunPython.noop),
    ]
