# Generated by Django 6.0 on 2026-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0041_company_and_province"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sindh_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Sindh %",
                    ),
                ),
                (
                    "punjab_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Punjab %",
                    ),
                ),
                (
                    "balochistan_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Balochistan %",
                    ),
                ),
                (
                    "kpk_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Khyber Pakhtunkhwa %",
                    ),
                ),
                (
                    "origin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Origin %",
                    ),
                ),
                (
                    "destination_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Destination %",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Tax Settings",
            },
        ),
    ]
