# Generated by Django 6.0 on 2026-09-26 07:13

from django.db import migrations, models


def islamabad_to_ict(apps, schema_editor):
    City = apps.get_model("masters", "City")
    City.objects.filter(name="ISLAMABAD").update(province="ICT")


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0042_tax_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxsettings",
            name="ict_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="ICT %"
            ),
        ),
        migrations.AddField(
            model_name="taxsettings",
            name="invoice_prefix",
            field=models.CharField(
                default="SFS-INV", max_length=15, verbose_name="Invoice # prefix"
            ),
        ),
        migrations.AddField(
            model_name="taxsettings",
            name="payment_terms_days",
            field=models.PositiveSmallIntegerField(
                default=30, verbose_name="Payment Terms (days)"
            ),
        ),
        migrations.AddField(
            model_name="taxsettings",
            name="provider_address",
            field=models.TextField(
                default="PLOT SURVEY # 334, NEAR AMAN TECH BUILDING, OPPOSITE TO CBM COLLEGE, KORANGI CREEK ROAD, KARACHI, SINDH, PAKISTAN",
                verbose_name="Service Provider Address",
            ),
        ),
        migrations.AddField(
            model_name="taxsettings",
            name="provider_name",
            field=models.CharField(
                default="SWIFT FREIGHT SOLUTIONS",
                max_length=150,
                verbose_name="Service Provider Name",
            ),
        ),
        migrations.AddField(
            model_name="taxsettings",
            name="provider_ntn",
            field=models.CharField(
                default="F596261-2", max_length=30, verbose_name="NTN"
            ),
        ),
        migrations.AddField(
            model_name="taxsettings",
            name="provider_strn",
            field=models.CharField(
                default="S596261-2", max_length=30, verbose_name="STRN"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINDH", "Sindh"),
                    ("PUNJAB", "Punjab"),
                    ("ICT", "Islamabad Capital Territory"),
                    ("KPK", "Khyber Pakhtunkhwa"),
                    ("BALOCHISTAN", "Balochistan"),
                ],
                max_length=15,
            ),
        ),
        migrations.RunPython(islamabad_to_ict, migrations.RunPython.noop),
    ]
