# Generated by Django 6.0 on 2026-09-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0043_sales_tax_invoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxsettings",
            name="destination_percent",
        ),
        migrations.RemoveField(
            model_name="taxsettings",
            name="origin_percent",
        ),
    ]
