# Generated by Django 6.0 on 2026-09-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0044_tax_partial_uses_province_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINDH", "Sindh"),
                    ("PUNJAB", "Punjab"),
                    ("ICT", "ICT (Islamabad Capital Territory)"),
                    ("KPK", "KPK (Khyber Pakhtoon Khuwa)"),
                    ("BALOCHISTAN", "Balochistan"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="taxsettings",
            name="kpk_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="KPK (Khyber Pakhtoon Khuwa) %",
            ),
        ),
    ]
