# Generated by Django 6.0 on 2026-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0045_province_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxsettings",
            name="invoice_notes",
            field=models.TextField(blank=True, verbose_name="Default invoice notes"),
        ),
    ]
