# Generated by Django 6.0 on 2026-09-26 08:16

from django.db import migrations, models


def fill_blank_notes(apps, schema_editor):
    from masters.models import DEFAULT_INVOICE_NOTES
    TaxSettings = apps.get_model("masters", "TaxSettings")
    TaxSettings.objects.filter(invoice_notes="").update(invoice_notes=DEFAULT_INVOICE_NOTES)


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0046_invoice_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxsettings",
            name="invoice_notes",
            field=models.TextField(
                blank=True,
                default="This is a computer-generated invoice and does not require a signature.\nFor detailed trip information, please refer to Page 2.\nAny discrepancy must be reported within 3 days of receiving this invoice.",
                verbose_name="Default invoice notes",
            ),
        ),
        migrations.RunPython(fill_blank_notes, migrations.RunPython.noop),
    ]
