# Generated by Django 6.0 on 2026-09-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0047_default_invoice_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxsettings",
            name="sales_tax_no",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Sales Tax No."
            ),
        ),
    ]
