# Generated by Django 6.0 on 2026-09-26 12:07

from django.db import migrations, models


OLD_DEFAULT = (
    "This is a computer-generated invoice and does not require a signature.\n"
    "For detailed trip information, please refer to Page 2.\n"
    "Any discrepancy must be reported within 3 days of receiving this invoice."
)


def use_template_wording(apps, schema_editor):
    """Move Tax-menu notes still on the earlier default over to the wording of the
    invoice template ("system-generated ... Please notify us of any discrepancies ...")."""
    from masters.models import DEFAULT_INVOICE_NOTES
    TaxSettings = apps.get_model("masters", "TaxSettings")
    for stale in (OLD_DEFAULT, ""):
        TaxSettings.objects.filter(invoice_notes=stale).update(invoice_notes=DEFAULT_INVOICE_NOTES)


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0048_sales_tax_no_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxsettings",
            name="invoice_notes",
            field=models.TextField(
                blank=True,
                default="This is a system-generated invoice and does not require a signature.\nFor detailed trip information, please refer to Page 2.\nPlease notify us of any discrepancies within 3 days of receiving this invoice.",
                verbose_name="Default invoice notes",
            ),
        ),
        migrations.RunPython(use_template_wording, migrations.RunPython.noop),
    ]
