# Generated by Django 5.2.16 on 2026-10-02 06:37

from django.db import migrations, models


def blank_ntn_to_null(apps, schema_editor):
    # an NTN saved as an empty string becomes NULL, like new blank ones
    apps.get_model("masters", "Client").objects.filter(ntn="").update(ntn=None)


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0049_template_invoice_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ntn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NTN #'),
        ),
        migrations.RunPython(blank_ntn_to_null, migrations.RunPython.noop),
    ]
