# Generated by Django 6.0 on 2026-02-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress (On Road)"),
                            ("returning", "Returning"),
                            ("completed", "Completed (Back to Base)"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("job_date", models.DateField(auto_now_add=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Voyage related notes (e.g., Gari ki condition ya driver ka naam)",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="masters.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operational Job",
                "verbose_name_plural": "Operational Jobs",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="operations.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trip_no",
                    models.CharField(blank=True, editable=False, max_length=50),
                ),
                ("trip_date", models.DateField()),
                ("bilty_number", models.CharField(max_length=50)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "detention",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "freight",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="masters.client",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.driver",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="operations.job",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="masters.route"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.vehicle",
                    ),
                ),
            ],
        ),
    ]
