# Generated by Django 6.0 on 2026-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="driver",
        ),
        migrations.AlterField(
            model_name="job",
            name="remarks",
            field=models.TextField(blank=True, help_text="Voyage related notes"),
        ),
    ]
