# Generated by Django 6.0 on 2026-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_remove_trip_driver_alter_job_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="freight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
