# Generated by Django 6.0 on 2026-07-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_alter_trip_freight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="freight",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
    ]
