# Generated by Django 6.0 on 2026-08-11 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0032_alter_route_tt_hours"),
        ("operations", "0004_alter_trip_freight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trip",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="trip",
            name="detention",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="rate",
        ),
        migrations.AddField(
            model_name="job",
            name="trip_advance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Trip Advance"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="additional_charges",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="trip",
            name="arrival_meter",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="arrived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Arrival Date & Time"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Delivery Date & Time"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="departed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Departure Date & Time"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="departure_meter",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="reached_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reached Date & Time"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="remarks",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="trip",
            name="bilty_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="trip",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="operations.job",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_trips",
                to="masters.route",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="JobExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toll_plaza",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "food",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "incentive",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "mobile_expense",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Mobile Expense",
                    ),
                ),
                (
                    "challan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tyre_expense",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "service",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "loading",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "offloading",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weighbridge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "maintenance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "labor_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Labor Charges",
                    ),
                ),
                (
                    "fuel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_breakdown",
                        to="operations.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobFuelEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "slip_number",
                    models.CharField(blank=True, max_length=50, verbose_name="Slip #"),
                ),
                (
                    "liters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Fuel in Liters"
                    ),
                ),
                ("fuel_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_entries",
                        to="operations.job",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_fuel_entries",
                        to="masters.fuelproduct",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_fuel_entries",
                        to="masters.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
    ]
