# Generated by Django 5.2.16 on 2026-09-23 09:58

import django.db.models.deletion
from django.db import migrations, models


def fill_from_vehicle(apps, schema_editor):
    # Existing trips start with their vehicle's current type.
    Trip = apps.get_model("operations", "Trip")
    for trip in Trip.objects.select_related("vehicle").filter(vehicle_type__isnull=True):
        if trip.vehicle.vehicle_type_id:
            Trip.objects.filter(pk=trip.pk).update(vehicle_type_id=trip.vehicle.vehicle_type_id)


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0034_alter_clientrate_current_fuel_price_and_more'),
        ('operations', '0005_alter_trip_options_remove_trip_detention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='masters.vehicletype'),
        ),
        migrations.RunPython(fill_from_vehicle, migrations.RunPython.noop),
    ]
