# Generated by Django 6.0 on 2026-09-24 08:42

import django.db.models.deletion
from django.db import migrations, models


CLIENT_NAME = "Five Star 3PL SERVICES"


def tag_five_star_trips_assia(apps, schema_editor):
    """Trips already booked for Five Star were priced on the rates that are now
    tagged ASSIA - tag them ASSIA too so they keep their freight."""
    Client = apps.get_model("masters", "Client")
    ClientSubCategory = apps.get_model("masters", "ClientSubCategory")
    Trip = apps.get_model("operations", "Trip")
    client = Client.objects.filter(name__iexact=CLIENT_NAME).first()
    assia = ClientSubCategory.objects.filter(client=client, name="ASSIA").first() if client else None
    if assia:
        Trip.objects.filter(client=client, sub_category__isnull=True).update(sub_category=assia)


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0036_client_sub_category"),
        ("operations", "0006_trip_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="masters.clientsubcategory",
                verbose_name="Sub-Category",
            ),
        ),
        migrations.RunPython(tag_five_star_trips_assia, migrations.RunPython.noop),
    ]
