# Generated by Django 6.0 on 2026-09-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0038_stopover"),
        ("operations", "0007_client_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="stopover_charges",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="trip",
            name="stopover_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stopover_trips",
                to="masters.city",
                verbose_name="Stopover City",
            ),
        ),
    ]
