# Generated by Django 6.0 on 2026-09-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_generated_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedinvoice",
            name="payment_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="generatedinvoice",
            name="period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedinvoice",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generatedinvoice",
            name="invoice_no",
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
