# Generated by Django 6.0 on 2026-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0010_sales_tax_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedinvoice",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
