# Generated by Django 6.0 on 2026-09-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0011_invoice_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedinvoice",
            name="sales_tax_no",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
