# Generated by Django 6.0 on 2026-09-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0049_template_invoice_notes"),
        ("operations", "0012_sales_tax_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedinvoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_invoices",
                to="masters.company",
            ),
        ),
    ]
