# Generated by Django 6.0 on 2026-09-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0049_template_invoice_notes"),
        ("operations", "0013_invoice_company_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedinvoice",
            name="recipient_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_invoices",
                to="masters.client",
            ),
        ),
    ]
