# Generated by Django 6.0 on 2026-09-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0015_invoice_provider_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedinvoice",
            name="provider_client",
        ),
    ]
