# Generated by Django 5.2.16 on 2026-09-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0049_template_invoice_notes'),
        ('operations', '0017_release_review_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rental_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_jobs', to='masters.vendor', verbose_name='Rental Supplier'),
        ),
    ]
