# Generated by Django 5.2.16 on 2026-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_job_rental_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexpense',
            name='trip_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Trip Fare'),
        ),
    ]
