# Generated by Django 5.2.16 on 2026-09-29 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0049_template_invoice_notes'),
        ('operations', '0019_jobexpense_trip_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rental_month',
            field=models.DateField(blank=True, null=True, verbose_name='Rental Month'),
        ),
        migrations.AddField(
            model_name='job',
            name='rental_pool',
            field=models.BooleanField(default=False, verbose_name='Monthly rental job'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Trip Fare'),
        ),
        migrations.AlterField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='masters.vehicle'),
        ),
    ]
