# Generated by Django 5.2.16 on 2026-09-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_monthly_rental_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_fuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fuel'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_loading',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Loading'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_offloading',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Offloading'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_weighbridge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Weighbridge'),
        ),
    ]
