# Generated by Django 5.2.16 on 2026-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_trip_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='auto_times',
            field=models.BooleanField(default=False, verbose_name='Auto'),
        ),
    ]
